input {
  beats {
        port => 5044
        }
}

output {
  elasticsearch {
    index => "system_logs"
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "x69wYEAMUV10aSUn*elh"
    ssl => true
    ssl_certificate_verification => false
  }
  # Thêm output debug
  stdout { codec => rubydebug }
}