# /etc/wireguard/wg0.conf
[Interface]
# VM1 WireGuard IP
Address = 10.10.0.1/24
ListenPort = 51820
PrivateKey = CAvsVgrUdiqPSzwdNGLnoHYBKKcEHAjb2dkjqw5CUXA=

# NAT: cho phép peers truy cập internet qua VM1 (tùy chọn)
# PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; \
#            iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# PostDown  = iptables -D FORWARD -i wg0 -j ACCEPT; \
#            iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# ─── Peer: Wazuh Agent 1 ───
[Peer]
PublicKey = gOexCXBBpee3o2bS4oIwGYOA2hFids3KVJOvb5HR6lE=
AllowedIPs = 10.10.0.10/32
Endpoint = ?
PersistentKeepalive = 25